# Generated by Django 3.2.4 on 2021-07-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='Tournaments',
        ),
    ]
