# Generated by Django 3.2.4 on 2021-07-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210704_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams_Tournaments',
        ),
    ]
