# Generated by Django 3.2.4 on 2021-07-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_nft_teams_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
